use grub_boot_reader::{MenuNode, parse_grub_cfg};

const REALISTIC_GRUB_CFG: &str = r#"
#
# DO NOT EDIT THIS FILE
#
# It is automatically generated by grub-mkconfig using templates
# from /etc/grub.d and settings from /etc/default/grub
#

### BEGIN /etc/grub.d/10_linux ###
menuentry 'Ubuntu' --class ubuntu --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-simple-5452f864-16a7-47b2-bdcf-cc7728ef28ab' {
	recordfail
	load_video
	gfxmode $linux_gfx_mode
	insmod gzio
	if [ x$grub_platform = xx86_64-efi ]; then
		insmod part_gpt
		insmod ext2
	fi
	linux	/boot/vmlinuz-6.8.0-40-generic root=UUID=5452f864-16a7-47b2-bdcf-cc7728ef28ab ro quiet splash $vt_handoff
	initrd	/boot/initrd.img-6.8.0-40-generic
}
submenu 'Advanced options for Ubuntu' $menuentry_id_option 'gnulinux-advanced-5452f864-16a7-47b2-bdcf-cc7728ef28ab' {
	menuentry 'Ubuntu, with Linux 6.8.0-40-generic' --class ubuntu --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-6.8.0-40-generic-advanced-5452f864-16a7-47b2-bdcf-cc7728ef28ab' {
		linux	/boot/vmlinuz-6.8.0-40-generic root=UUID=5452f864-16a7-47b2-bdcf-cc7728ef28ab ro quiet splash $vt_handoff
		initrd	/boot/initrd.img-6.8.0-40-generic
	}
	menuentry 'Ubuntu, with Linux 6.8.0-40-generic (recovery mode)' --class ubuntu --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-6.8.0-40-generic-recovery-5452f864-16a7-47b2-bdcf-cc7728ef28ab' {
		linux	/boot/vmlinuz-6.8.0-40-generic root=UUID=5452f864-16a7-47b2-bdcf-cc7728ef28ab ro recovery nomodeset dis_ucode_ldr
		initrd	/boot/initrd.img-6.8.0-40-generic
	}
}
### END /etc/grub.d/10_linux ###

### BEGIN /etc/grub.d/30_os-prober ###
menuentry 'Windows Boot Manager (on /dev/nvme0n1p1)' --class windows --class os $menuentry_id_option 'osprober-efi-645E-5D3E' {
	insmod part_gpt
	insmod fat
	search --no-floppy --fs-uuid --set=root 645E-5D3E
	chainloader /EFI/Microsoft/Boot/bootmgfw.efi
}
### END /etc/grub.d/30_os-prober ###
"#;

#[test]
fn test_parse_grub_cfg_hierarchy() {
    let nodes = parse_grub_cfg(REALISTIC_GRUB_CFG);

    // 顶层应有 3 个节点：Ubuntu, Advanced options 子菜单, Windows Boot Manager
    assert_eq!(nodes.len(), 3);

    // 验证第一个条目
    match &nodes[0] {
        MenuNode::Entry(entry) => {
            assert_eq!(entry.title, "Ubuntu");
            assert_eq!(entry.full_path, "Ubuntu");
            assert_eq!(
                entry.id.as_deref(),
                Some("gnulinux-simple-5452f864-16a7-47b2-bdcf-cc7728ef28ab")
            );
            assert!(entry.classes.contains(&"ubuntu".to_string()));
            assert!(entry.classes.contains(&"os".to_string()));
            assert_eq!(
                entry.kernel_path.as_deref(),
                Some("/boot/vmlinuz-6.8.0-40-generic")
            );
            assert_eq!(
                entry.initrd_path.as_deref(),
                Some("/boot/initrd.img-6.8.0-40-generic")
            );
            assert_eq!(
                entry.root_uuid.as_deref(),
                Some("5452f864-16a7-47b2-bdcf-cc7728ef28ab")
            );
            assert!(
                entry
                    .cmdline_params
                    .as_ref()
                    .unwrap()
                    .contains("quiet splash")
            );
        }
        _ => panic!("预期为普通引导条目"),
    }

    // 验证子菜单
    match &nodes[1] {
        MenuNode::Submenu {
            title,
            children,
            full_path,
            ..
        } => {
            assert_eq!(title, "Advanced options for Ubuntu");
            assert_eq!(full_path, "Advanced options for Ubuntu");
            assert_eq!(children.len(), 2);

            // 检查子菜单项中的路径层级
            if let MenuNode::Entry(sub_entry) = &children[0] {
                assert_eq!(sub_entry.title, "Ubuntu, with Linux 6.8.0-40-generic");
                assert_eq!(
                    sub_entry.full_path,
                    "Advanced options for Ubuntu>Ubuntu, with Linux 6.8.0-40-generic"
                );
            } else {
                panic!("子菜单内预期为普通引导条目");
            }

            if let MenuNode::Entry(sub_entry) = &children[1] {
                assert_eq!(
                    sub_entry.title,
                    "Ubuntu, with Linux 6.8.0-40-generic (recovery mode)"
                );
                assert_eq!(
                    sub_entry.full_path,
                    "Advanced options for Ubuntu>Ubuntu, with Linux 6.8.0-40-generic (recovery mode)"
                );
            } else {
                panic!("子菜单内预期为普通引导条目");
            }
        }
        _ => panic!("预期为子菜单"),
    }

    // 验证 Windows 条目
    match &nodes[2] {
        MenuNode::Entry(entry) => {
            assert_eq!(entry.title, "Windows Boot Manager (on /dev/nvme0n1p1)");
            assert_eq!(entry.full_path, "Windows Boot Manager (on /dev/nvme0n1p1)");
            assert!(entry.classes.contains(&"windows".to_string()));
            assert_eq!(
                entry.chainloader_path.as_deref(),
                Some("/EFI/Microsoft/Boot/bootmgfw.efi")
            );
            assert_eq!(entry.root_uuid.as_deref(), Some("645E-5D3E"));
        }
        _ => panic!("预期为 Windows 引导条目"),
    }
}

#[test]
fn test_collect_all_entries() {
    let nodes = parse_grub_cfg(REALISTIC_GRUB_CFG);
    let mut all_entries = Vec::new();
    for node in &nodes {
        all_entries.extend(node.collect_entries());
    }

    // 总共应收集到 4 个叶子启动项
    assert_eq!(all_entries.len(), 4);
    assert_eq!(all_entries[0].title, "Ubuntu");
    assert_eq!(all_entries[1].title, "Ubuntu, with Linux 6.8.0-40-generic");
    assert_eq!(
        all_entries[2].title,
        "Ubuntu, with Linux 6.8.0-40-generic (recovery mode)"
    );
    assert_eq!(
        all_entries[3].title,
        "Windows Boot Manager (on /dev/nvme0n1p1)"
    );
}
