[package]
name = "grub-config-parser"
description = "保留格式与注释的 GRUB 默认配置文件解析器"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[dependencies]

[dev-dependencies]
proptest.workspace = true
